### ISSUE TITLE
box-cutter/ubuntu1610 not working

### ISSUE THREAD

**Issue by RevanthReddyT** [g0t4/aspnetcore-generator-api#6]
Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'w1' up with 'virtualbox' provider...
Bringing machine 'w2' up with 'virtualbox' provider...
==> m1: Importing base box 'box-cutter/ubuntu1610'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'box-cutter/ubuntu1610' is up to date...
==> m1: Setting the name of the VM: swarm_m1_1510270504981_15294
==> m1: Clearing any previously set network interfaces...
==> m1: Preparing network interfaces based on configuration...
    m1: Adapter 1: nat
    m1: Adapter 2: bridged
==> m1: Forwarding ports...
    m1: 22 (guest) => 2222 (host) (adapter 1)
==> m1: Running 'pre-boot' VM customizations...
==> m1: Booting VM...
==> m1: Waiting for machine to boot. This may take a few minutes...
    m1: SSH address: 127.0.0.1:2222
    m1: SSH username: vagrant
    m1: SSH auth method: private key
    m1: 
    m1: Vagrant insecure key detected. Vagrant will automatically replace
    m1: this with a newly generated keypair for better security.
    m1: 
    m1: Inserting generated public key within guest...
    m1: Removing insecure key from the guest if it's present...
    m1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> m1: Machine booted and ready!
==> m1: Checking for guest additions in VM...
==> m1: Setting hostname...
==> m1: Configuring and enabling network interfaces...
==> m1: Mounting shared folders...
    m1: /vagrant => /Users/revantht/Projects/Innominds/Mobilogix/innominds_mobilogix_server/infra/swarm
==> m1: Running provisioner: shell...
    m1: Running: /var/folders/t8/gv0q03sd7vz0m17qd6g33b0r0000gn/T/vagrant-shell20171110-36080-1eq72r9.sh
==> m1: # Executing docker install script, commit: 49ee7c1
==> m1: 
==> m1: Either your platform is not easily detectable or is not supported by this
==> m1: installer script.
==> m1: Please visit the following URL for more detailed installation instructions:
==> m1: 
==> m1: https://docs.docker.com/engine/installation/
==> m1: usermod: group 'docker' does not exist
==> m1: /tmp/vagrant-shell: line 13: /etc/docker/daemon.json: No such file or directory
==> m1: --2017-11-09 23:35:34--  https://raw.githubusercontent.com/docker/docker/v17.05.0-ce/contrib/init/systemd/docker.service.rpm
==> m1: Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 
==> m1: 151.101.8.133
==> m1: Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.8.133|:443... 
==> m1: connected.
==> m1: HTTP request sent, awaiting response... 
==> m1: 200 OK
==> m1: Length: 
==> m1: 1140
==> m1:  (1.1K)
==> m1:  [text/plain]
==> m1: Saving to: '/lib/systemd/system/docker.service'
==> m1: 
==> m1:      0K
==> m1:  
==> m1: .
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1:  
==> m1: 100%
==> m1:   203M
==> m1: =0s
==> m1: 
==> m1: 2017-11-09 23:35:35 (203 MB/s) - '/lib/systemd/system/docker.service' saved [1140/1140]
==> m1: Job for docker.service failed because the control process exited with error code.
==> m1: See "systemctl status docker.service" and "journalctl -xe" for details.
==> m1: Reading package lists...
==> m1: Building dependency tree...
==> m1: E
==> m1: : 
==> m1: Unable to locate package ipvsadm
==> m1: E
==> m1: : 
==> m1: Unable to locate package tree
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by g0t4** [comment]
This repo has a fix for this.


----------
On Thu, Nov 9, 2017 at 18:45, Revanth Reddy T <notifications@github.com>
wrote:

Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'w1' up with 'virtualbox' provider...
Bringing machine 'w2' up with 'virtualbox' provider...
==> m1: Importing base box 'box-cutter/ubuntu1610'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'box-cutter/ubuntu1610' is up to date...
==> m1: Setting the name of the VM: swarm_m1_1510270504981_15294
==> m1: Clearing any previously set network interfaces...
==> m1: Preparing network interfaces based on configuration...
m1: Adapter 1: nat
m1: Adapter 2: bridged
==> m1: Forwarding ports...
m1: 22 (guest) => 2222 (host) (adapter 1)
==> m1: Running 'pre-boot' VM customizations...
==> m1: Booting VM...
==> m1: Waiting for machine to boot. This may take a few minutes...
m1: SSH address: 127.0.0.1:2222
m1: SSH username: vagrant
m1: SSH auth method: private key
m1:
m1: Vagrant insecure key detected. Vagrant will automatically replace
m1: this with a newly generated keypair for better security.
m1:
m1: Inserting generated public key within guest...
m1: Removing insecure key from the guest if it's present...
m1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> m1: Machine booted and ready!
==> m1: Checking for guest additions in VM...
==> m1: Setting hostname...
==> m1: Configuring and enabling network interfaces...
==> m1: Mounting shared folders...
m1: /vagrant =>
/Users/revantht/Projects/Innominds/Mobilogix/innominds_mobilogix_server/infra/swarm
==> m1: Running provisioner: shell...
m1: Running:
/var/folders/t8/gv0q03sd7vz0m17qd6g33b0r0000gn/T/vagrant-shell20171110-36080-1eq72r9.sh
==> m1: # Executing docker install script, commit: 49ee7c1
==> m1:
==> m1: Either your platform is not easily detectable or is not supported
by this
==> m1: installer script.
==> m1: Please visit the following URL for more detailed installation
instructions:
==> m1:
==> m1: https://docs.docker.com/engine/installation/
==> m1: usermod: group 'docker' does not exist
==> m1: /tmp/vagrant-shell: line 13: /etc/docker/daemon.json: No such file
or directory
==> m1: --2017-11-09 23:35:34--
https://raw.githubusercontent.com/docker/docker/v17.05.0-ce/contrib/init/systemd/docker.service.rpm
==> m1: Resolving raw.githubusercontent.com (raw.githubusercontent.com)...
==> m1: 151.101.8.133
==> m1: Connecting to raw.githubusercontent.com (raw.githubusercontent.com
)|151.101.8.133|:443...
==> m1: connected.
==> m1: HTTP request sent, awaiting response...
==> m1: 200 OK
==> m1: Length:
==> m1: 1140
==> m1: (1.1K)
==> m1: [text/plain]
==> m1: Saving to: '/lib/systemd/system/docker.service'
==> m1:
==> m1: 0K
==> m1:
==> m1: .
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1:
==> m1: 100%
==> m1: 203M
==> m1: =0s
==> m1:
==> m1: 2017-11-09 23:35:35 (203 MB/s) -
'/lib/systemd/system/docker.service' saved [1140/1140]
==> m1: Job for docker.service failed because the control process exited
with error code.
==> m1: See "systemctl status docker.service" and "journalctl -xe" for
details.
==> m1: Reading package lists...
==> m1: Building dependency tree...
==> m1: E
==> m1: :
==> m1: Unable to locate package ipvsadm
==> m1: E
==> m1: :
==> m1: Unable to locate package tree
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/6>, or mute the
thread

**Comment by RevanthReddyT** [comment]
Which repo you are talking about. 10 days back it worked but today it is not working

**Comment by RevanthReddyT** [comment]
box-cutter/ubuntu1610 is not able to run docker.

Revanths-MacBook-Pro-2:swarm revantht$ export DOCKER_HOST=192.168.0.201
Revanths-MacBook-Pro-2:swarm revantht$ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon at tcp://192.168.0.201:2375. Is the docker daemon running?

**Comment by RevanthReddyT** [comment]
==> m1: Job for docker.service failed because the control process exited with error code.

How to solve this issue? Please help me

**Comment by g0t4** [comment]
What’s the error code/message lead you to?


----------
On Fri, Nov 10, 2017 at 17:24, Revanth Reddy T <notifications@github.com>
wrote:

==> m1: Job for docker.service failed because the control process exited
with error code.

How to solve this issue? Please help me

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/g0t4/aspnetcore-generator-api/issues/6#issuecomment-343603177>,
or mute the thread

**Comment by semihtuzunkan** [comment]
can u help this ?


Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'w1' up with 'virtualbox' provider...
Bringing machine 'w2' up with 'virtualbox' provider...
==> m1: Box 'box-cutter/ubuntu1604' could not be found. Attempting to find and install...
    m1: Box Provider: virtualbox
    m1: Box Version: >= 0
==> m1: Loading metadata for box 'box-cutter/ubuntu1604'
    m1: URL: https://vagrantcloud.com/box-cutter/ubuntu1604
==> m1: Adding box 'box-cutter/ubuntu1604' (v2.0.26) for provider: virtualbox
    m1: Downloading: https://vagrantcloud.com/box-cutter/boxes/ubuntu1604/versions/2.0.26/providers/virtualbox.box
#<Thread:0x00005574aeddde48@/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:71 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	37: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	36: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `action'
	35: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:188:in `call'
	34: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:592:in `lock'
	33: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:202:in `block in action'
	32: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:227:in `action_raw'
	31: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	30: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	29: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	28: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	27: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	26: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	25: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	24: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `run'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/busy.rb:19:in `busy'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builder.rb:116:in `call'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/warden.rb:34:in `call'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:118:in `call'
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:283:in `add_from_metadata'
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:330:in `box_add'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:330:in `each'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:338:in `block in box_add'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:463:in `download'
	 1: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/downloader.rb:147:in `download!'
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/downloader.rb:259:in `execute_curl': An error occurred while downloading the remote file. The error (Vagrant::Errors::DownloaderError)
message, if any, is reproduced below. Please fix this error and try
again.

Could not resolve host: cdn.boxcutter.io
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Could not resolve host: cdn.boxcutter.io
